function X=Logistic_dyn(x,lambda,n,noise)
%the function takes as inputs
%x: intial point in [0,1]
%lambda= parameter of the Logistic map
%n= number of points of the series
%noise = vector of a realization noise process whose length is equal to n 
%the noise-free series is generated by setting noise=0.

%the ouput X is a realization of a Logistic map orbit perturbed by an
%imposed noise
X(1)=x;
for j=2:n
    X(j)=mod(lambda*X(j-1)*(1-X(j-1))+noise(j),1);
 
end
end
