function [X]=P_M(x,alpha,N,noise)
%the function takes as inputs
%x: intial point in [0,1]
%alpha= parameter of the Logistic map
%N= number of points of the series
%noise = vector of a realization noise process whose length is equal to n 
%the noise-free series is generated by setting noise=0.

%the ouput X is a realization of a Pomeau-Manneville map orbit perturbed by an
%imposed noise
X(1)=mod(x+noise(1),1);
for j=2:N
X(j)=mod(X(j-1)+X(j-1)^(alpha)+noise(j),1);
end